---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-config-prod
  namespace: monitoring-prod
spec:
  encryptedData:
    alertmanager.yaml: AgC/WTpySpHjMrhhDiiUq8VkuHjNWq4ccY2/BwKIIAaZaui64y9kANvxrJ88wqLsVruiFxKv7PHbanUmg8mEUX4sxYESd4hyElJSVlziwHGwOqAoB2NEHUnwJqUXINqm3v1TclFR9dyxMqTtExfDAQ02zUFWQnbDfoaDXSjkVxz3GZShcyF5b2FIw16axWBh7CqNWCGclptvec3UFiDo2nXDrEhWyCdah+Gv7C5qKvqlzI2MJJ1IXIlO7iV/fLX3UlL2jkX04ru2acVK/kDw2pTJTyr1u4FVG7H+RFZa7Sdr4osA5bhJhhGOpxE57fCgDP2MJ+jQSxMuHkpiFknNpVeOEMZK6B66Ajhufd3PTgQqIBPxdcvwNyhu23waQjmLSSw5VqDcXDLFimsDemmn2ssuBRC4Ce8RRwzzvOUm9R5T7Gw4SLISrEkF//1uznoz/RO5E6YRncWADLkqi4s8um26uuGOmqLPyCIJ01cObLPr7HmCmduepEeYzFG+c6grrPSvxMvuoN+V+b+KulB1XTNzl5JaF0uwLnsU2uPmKoA/HUIYY7RhmbJsENf6eVkLgD66rTHcqF2pwX3LBKrwS7JrHxFOOPfyzDmfpJj50Gexa7zp/YUfExRYgXBu04HcYEXphIoi0l3VHlMzEzFjXLsxrkXz5BzOtj3TySWvyG2qUFItOuhB5Vs6SSgGqwHciAd/6lYG2GaK/yaMZdtLQshKOSLx/aHE9XgihFPIpej1i0N3JZjiSldxMM4nFbH8Qs46Y5lFRKS39J/gjdV8x92qapaVDeEpp0ebF7oMpvLF+Nr52e5PSkHV29UXz8VYNNn3uGoiW/Fvkxi+uD5mz9s/UZ2gNwXacTjwEMobllOcT1diK8K827A9I8LbddFwVzevkti6J8r+2P6INHNHq8tQ6P1+yB1R9USEH5QFwv4ZCmzNdkFCBjAWWFRhRB75kWtDULqNceqhiZWVzLPYQD5u/N35HhTQfJDyxJQ0sZlax/2rWak3G8zk8j4ztwyQbB+PyNbGG0/IxpN2fCnVBlbgrl3z/YRv/jSBohUusBoyBOUkOYBzHCqg9KxBvYQQsN9aeLZ1u1Q0RtcNyXt5zogXsHrn3oViAE/Vul2XC8qSRJ0pfajAIsHCE6lhxaVMvswossYvaK3XtWPvsH4ccD4Xyhyr9wf6YvoyWdp5VoHc2Nj7it/zJZnYuAh7SEvJuWWkYlhFVzZYdp+j5Kp73lU0VP5LsX1QLa6f0V4SoAnzKWb+/5HCKSrxaPWrItbAVsfhEjNzstSn0P7iBwElfTknJ/hCpUvJkdG/aCW7kB/AOR1ILSY+d1o5d8yf+qaSLhA/SjkQo1RJWC2OzQebTxnKrawpDqxQqBrwGHsBqskNP/8ZuDJIwGqD1b0gemQohGTqoZcdeMIWg45sPXTOLpZUsOoTcSVvZpnyNoKRHrf4itjD5iUkga2AzTtPV2Zp1y/LpaJPigpLGnpTU/iRKJMpVpzrh/BlLEXAj3ozKVljOKdk9Ac9gom68OAm6Pe4EjNMqR9F0if3iacjuUuiXZ6oHKw4
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-config-prod
      namespace: monitoring-prod
