{{- if .Values.featureStore.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-store-resources
  namespace: {{ .Release.Namespace }}
data:
  user_features.schema.json: |
{{ .Values.featureStore.userFeaturesSchemaJson | indent 4 }}
  metadata.json.j2: |
{{ .Values.featureStore.metadataJsonJ2 | indent 4 }}
{{- end }}

