apiVersion: apps/v1
kind: Deployment
metadata:
  name: feast-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feast-server
  template:
    metadata:
      labels:
        app: feast-server
    spec:
      containers:
        - name: feast-server
          image: {{ .Values.feastServer.image }}
          ports:
            - containerPort: {{ .Values.feastServer.port }}
          env:
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /root/.aws/credentials
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.aws.region }}
            - name: AWS_REGION
              value: {{ .Values.aws.region }}
          volumeMounts:
            - name: feast-repo
              mountPath: /feast-repo/feature_store.yaml
              subPath: feature_store.yaml
              readOnly: true
            - name: feast-repo
              mountPath: /feast-repo/repo.py
              subPath: repo.py
              readOnly: true

          command:
            - /bin/sh
            - -c
          args:
            - |
              set -euxo pipefail
              
              echo "[A] list /feast-repo"
              ls -al /feast-repo
              test -f /feast-repo/feature_store.yaml
              test -f /feast-repo/repo.py
              
              rm -rf /tmp/feast-repo
              mkdir -p /tmp/feast-repo
              cp -v /feast-repo/* /tmp/feast-repo/
              
              echo "[B] list /tmp/feast-repo"
              ls -al /tmp/feast-repo
              test -f /tmp/feast-repo/feature_store.yaml
              test -f /tmp/feast-repo/repo.py
              
              cd /tmp/feast-repo
              feast apply
              feast serve --host 0.0.0.0 --port 6566

      volumes:
        - name: feast-repo
          configMap:
            name: feast-repo
        - name: aws-credentials
          secret:
            secretName: {{ .Values.aws.credentialsSecretName }}
