apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - fastapi-dev-sm.yaml
  - fastapi-dev-pm.yaml
  - rules/fastapi-alerts.yaml
  - rules/triton-alerts.yaml
  - sealed-secrets
