{{- $db := .Values.dbConfig | default dict -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ (get $db "configMapName" | default "mlflow-db-config") }}
  namespace: {{ .Release.Namespace }}
data:
  dbname: {{ (get $db "dbname" | default "mlflow") }}
  host: {{ (get $db "host" | default "postgres") }}
  port: "{{ (get $db "port" | default 5432) }}"
