---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-config-dev
  namespace: monitoring-dev
spec:
  encryptedData:
    alertmanager.yaml: AgAtlV5yOugOnbjFCak3DTBPMtISqejTiIKClsXlpAbz4286wutf0V9iEF8KPrnoR3vaD6lE+aUCaI8zA+U8XG0WWFW3fHVET6W55rNupYmUt+BxS/N1htn3kdUbIZjpMiO7FmQpAcVC951FkgfGguPVxYI4Fn6QtIYObsV1AWOpPpnR4SRK/A5BoSK5AtkFe0xFwSG4KApWxIFsNe8h0iWCKrdjMt03oVS7SUld2VE9oiDC2jxwq7AlnQ1rqdhsF1a0qVKqZbINYu6qq8DtX7gYxDxf2Iyjx89KpmoAhWmbxuIV1ONqR5ZnncuuBeUeSWQMecdAR7ln5n5ARdiwykKfdCDP0cBl2wUlx12lcwAozDu7D8BbcqPBKCjHoD+dJHicHpRRJ4z/r30GqW0RfE+MwsbjzXUqhsyPpCqD/2slKnQobL+7tkNcKFuM8sdPjDHL/7XXMhBPLSJF5qv1iIfnZy6i0cJhD4bY9PQWFEFr3siu38dTg/BaM/+fqOSukhbgduhw4d9fbKSvB3UTGSYT8A1fwxfX1JJKOPR6A+kD+yMJ53gsOiAMJ122goFp9FCiEHD5kpEZ31tw9UWIc1tGYaElbkERb25KCUQfLH4EkABm6bhphcl0WJlcO609lNT5GodQcLcIJYBh490fJTJXA2BUWti1C6kLBbyHXCu3bBOl3UK8x4LMJc/G2kbm3f+1sbKOsO8kms+I/5BdPLMCwa5o/1bpQXLTGESiuwM9sN+BICJgn8PEqwCyzXsUxPZ3R9UC+8webaYx/cHY5WRgp/fv4mXpiSTVGAjscUYPfsvnFYjtAB0HmAD7Uj0D1QCI0BKC8qqAHu3aX7wjxRqbcsUlIO6EeBPmzrBYEU1mPZsZxA6NQ7ggCsEbBetKs94YiMdWnQezgLhvTynOdzExUvGpo0ZVTUWpQHWqpYZsuG+yIiRP1ZB5uGSsBv92gmJgnzraBVYiiNcRp9NlFHYJJnqDwYj2sCzIZCjp8AF4bnVFuyrw0bfnmhdM0lAfF+ZYA+5wtsX7zdn49WnGFfL4IdIfy/XJHo62B0XbqOsuYxok0AeXaO7F3267gcs9/iIo5lfiKA1E5LbX9PFYea+IDSIFqbq0Fb/K09XJB2PyD8J9k4Y34NxCCwgl1bAsGgdaXBiMPr2ByDKBVjTjl3KObMv9VoanyMTzCbRKqIF6a5Lx3nmJYqz1VgWMm9/qcZFEB6jksrkeblZt53r18Er0jUbCZ25i/zm0a7KTxGHDIqczxmgWCLAdCOZhZlCQeWfArlqoS35VgwrDUGjeTK2f4orCp3RmJ9arOvM/0W2BotcZxwd5rjkGsJlfpT5pKfzk7z+iQHGjnmbHmlDl9r3VNCf7VF1F6Q6LnUmXvPN2qC76HeQJh48aAqjXKHF3MGbI2vQ383HZ7zGZWwTvU1YyYqraqnlVnxUJZ5C90XdQlhTASUnGRwm2C0+8HcpGC7zVrAVX8QOTtJw5/MqGNF3ARxv75H5SGnXBAPC5VXMo6HMnpCN5Z+u9fppZ+4NVi+0ZNqhmA1YdCSlW7sRA4F+YDx7xcOOCJ/IkGNgJMmDVjg==
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-config-dev
      namespace: monitoring-dev
