---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-config-dev
  namespace: monitoring-dev
spec:
  encryptedData:
    alertmanager.yaml: AgA5TrUCsW6aVCwFyi/k04TQqPJXV8gcmUeyOp8Vnen/ndFr5cjy4xcymyeFqRTE97WLlNscpF6kjtWe5KnpHRZHrk63UHNSBNARZ82PoxrwuvJe50e9cCjbp8tSQ5GNfcYdh7RHSoyDBepd5DziuCuQLcdF4tf6kGJyVmHnfmPGQW/Az/VHTUPF/FAkDt0/ZjzGFriYhPkxbofV/7YwCCkBj143QI/+Q1jmXpg01d+GIwOPXVZzLwiXQ/QLLD7yeoMzBY0V57DMM4yVZeqxAsYiFlEoTm1q2TDWbe2QWE/H2zRkWdLUwAjMLuxYYLWTWSxH1CUJQsFbRxX3IfDRIVFuD1WFkRVjxYg9Q7+ACWUmxz1SKIzyDbSQE2Sz+VI2NxBklzfvwT2vnR1z/MSepCpB1xLmON+SEtB9Y0AB17/ra0MA8WOID1qMAZs7d65CiIhX70zzMLKdntFpU2zH/cUEWQxYkiGJSS2AJhIZVstDCy3Y3oKUUQYfFmS8rKLiv0cUBBg4S7X3Hd3fxMpJ9mW57DSEGrqdHaDUTlDZVkDzqnZ0Yibjp3ZcTUKb6qXC7d8NoMNwjAKo/zx1J0TqJ4Tknti1zo0ne0EEmVkAxxA4g9m0QGu0PbIAa4HuDpisfM7MP/uGveiiDfXoIXsccOL0Not/O71CugVwxIAsxLPE3KsAToPFGQ1U0MMsd/Y8Ce4yiEwAYCBv6HxZGi74Ap+XoibamvkSXWvuO/FXThvufne2z9ptIJmUExU3Kb1nY7i/Baz7HEuRhwHQ5//qpiJPUAWztvjMw3xvwZcQULXvFWkCzRPwayZSop1e7nwDkvqiVK7e3E4X9pPmQpR5Xqz3ElvkypJZba/b0iEJ7QL8BWVqx4P2ftHyHSB4SkGA9BhMkg4e8bzI6EcHxGndlZe+hhBmRR6ygimrbuzCISBzX+wrgOaNSRV5M8poHmkJ8gXzD6z6KO78BDUFmA8G0PklSksAJFi3STBtPc11gMfrDzqkIvaFEfpVqZcxQ9cnGN3a2w/wbBCFbJqy3WPZEaSNFxjUe9SG0KiXvUMfBpKtkme2OUtl23k7RGTg8CwkPWKI4EGop9NbUjehJJs72PDTjgMaQBny+Goifvfu6IMDRsCH/g3QOOsNN+SzSp5Upvr1xn1jyqbIXuigXUVGfGg3SMfBcJ7xs/6Wiks+mgsG+WVmLVPG1T2PW6/9mJImnlg5WxUwuT67ANPNU9SXbGnYvt6Nf3kLedzH4XVBL6qyNZ0veacyplIGcf1YtGRDvZR/CIzMthqRuAYLpI6s0PMigQLzrICAFNHWOci0mOblpi1NG2zfu+MtBWclyRLayebJuYNTwMIZvzELj2J0TdqzOZkkv5k4KRAdWXm5LkiRV1uhXHI3scIA/Rvu/AYQIoFIk8M905k5feRgdFgtPBLgfWyT2g4sgR041xhW5o5lkQDY4JVC19Gn2f5PuxmKb8EvRfHt5U1bx7kU30p2/PBQMllhPjiO7q/nO/k46FC3pqP4ncX1WMR5Nr6mCYStGURwZtIbvdBqsG8jAKae84s=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-config-dev
      namespace: monitoring-dev
