apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  stack: optional
  scope: optional
  layer: optional

resources:
  # optional namespaces/secrets/env foundation
  - envs/optional-envs-dev.yaml
  - envs/optional-envs-prod.yaml

  # feast
  - feast/feast-dev.yaml
  - feast/feast-prod.yaml

  # monitoring
  - monitoring/monitoring-dev.yaml
  - monitoring/monitoring-prod.yaml

