{{- range .Values.ingresses }}
{{- $create := true -}}
{{- if hasKey .tls "createCertificate" -}}
{{- $create = .tls.createCertificate -}}
{{- end -}}
{{- if and .tls .tls.enabled .tls.secretName .tls.issuerName $create }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Release.Name }}-tls
  namespace: {{ $.Release.Namespace }}
spec:
  secretName: {{ .tls.secretName }}
  issuerRef:
    name: {{ .tls.issuerName }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .host }}
{{- end }}
{{- end }}

