{{- $svc := .Values.service | default dict -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
{{- include "fastapi.commonLabels" . | nindent 4 }}
spec:
  type: {{ (get $svc "type" | default "ClusterIP") }}
  selector:
{{- include "fastapi.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ (get $svc "port" | default 8000) }}
      targetPort: 8000
