{{- $metrics := .Values.metrics | default dict -}}
{{- $mon := .Values.monitoring | default dict -}}
{{- if (get $metrics "enabled" | default false) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-sm
  labels:
{{- include "fastapi.commonLabels" . | nindent 4 }}
    release: {{ (get $mon "releaseLabel" | default "monitoring") | quote }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
{{- include "fastapi.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ (get $metrics "path" | default "/metrics") }}
      interval: {{ (get $metrics "interval" | default "30s") | quote }}
      scrapeTimeout: {{ (get $metrics "scrapeTimeout" | default "10s") | quote }}
{{- end }}
