image:
  registry: docker.io
  repository: bitnami/minio
  tag: latest
  pullPolicy: IfNotPresent
auth:
  rootUser: minioadmin
  rootPassword: minioadmin

defaultBuckets: "loki"

persistence:
  enabled: true
  storageClass: nfs-core
  size: 10Gi

service:
  type: ClusterIP

console:
  enabled: false

