apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: redis
    releaseName: redis-dev
    namespace: feature-store-dev
    repo: https://charts.bitnami.com/bitnami
    version: 19.6.1
    valuesFile: values.yaml
