# mlflow-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
{{ include "mlflow.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "mlflow.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{ include "mlflow.labels" . | nindent 8 }}
    spec:
      containers:
        - name: mlflow
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
          command: ["mlflow", "server"]
          args:
            - "--backend-store-uri=postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
            - "--default-artifact-root={{ .Values.env.defaultArtifactRoot }}"
            - "--host=0.0.0.0"
            - "--port=5000"
            - "--serve-artifacts"
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbConfig.secretName }}
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbConfig.secretName }}
                  key: password
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.dbConfig.configMapName }}
                  key: host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.dbConfig.configMapName }}
                  key: port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.dbConfig.configMapName }}
                  key: dbname

          envFrom:
            - secretRef:
                name: aws-credentials-secret

          {{- if .Values.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}

