auth:
  rootUser: minioadmin
  rootPassword: minioadmin

defaultBuckets: "loki"

persistence:
  enabled: true
  storageClass: nfs-core
  size: 10Gi

service:
  type: ClusterIP

console:
  enabled: false

