apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  stack: baseline
  scope: baseline
  layer: baseline

resources:
  - baseline/appset-baseline.yaml
  - baseline/minio-dev.yaml
  - baseline/minio-prod.yaml

