apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-secrets
  - feature-store
  - storage/triton-model-repo/pv-pvc.yaml
  - triton-dev-triton-model-repo-dev-pv.yaml
  - triton-dev-triton-model-repo-pvc.yaml
