apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # 1) ArgoCD Project
  - project-dev.yaml
  - project-prod.yaml

  # 2) Namespace scaffolding (envs/* apply)
  - dev-namespaces.yaml
  - prod-namespaces.yaml

  # 3) Core AppSet
  - appset-core.yaml

  # 4) Optional prereqs (cluster base)
  - optional-prereqs/metallb-config.yaml

