apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # 0) ArgoCD Projects
  - project-bootstrap.yaml
  - project-dev.yaml
  - project-prod.yaml
  - project-optional.yaml
  - project-baseline.yaml

  # 1) Namespace scaffolding (envs/* apply)
  - dev-namespaces.yaml
  - dev-support.yaml
  - prod-namespaces.yaml
  - prod-support.yaml

  # 1.5) Core Storage (PV/PVC) - Triton model repo for Airflow dev/prod
  - storage/triton-model-repo/airflow-dev/pv-pvc.yaml
  - storage/triton-model-repo/airflow-prod/pv-pvc.yaml

  # 2) Core AppSet
  - appset-core.yaml

