apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  stack: core
  scope: core

resources:
  # 0) ArgoCD Projects
  - project-dev.yaml
  - project-prod.yaml
  - project-optional.yaml

  # 1) Namespace scaffolding (envs/* apply)
  - dev-namespaces.yaml
  - dev-support.yaml
  - prod-namespaces.yaml
  - prod-support.yaml

  # 2) Core AppSet
  - appset-core.yaml

