apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # 1) ArgoCD Project (먼저)
  - project-dev.yaml
  - project-prod.yaml

  # 2) Namespace scaffolding
  - dev-namespaces.yaml
  - prod-namespaces.yaml

  # 3) Core AppSet (생성기)
  - appset-core.yaml
