apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-aws-credentials-secret.yaml
  - sealed-fastapi-token-prod-secret.yaml
  - sealed-slack-webhook-prod-secret.yaml

