apiVersion: v1
kind: Service
metadata:
  name: feast-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: feast-server
  ports:
    - name: http
      port: {{ .Values.feastServer.port }}
      targetPort: {{ .Values.feastServer.port }}
