apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton
  labels:
{{ include "triton.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "triton.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{ include "triton.labels" . | nindent 8 }}
    spec:
      containers:
        - name: triton
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - tritonserver
            - --model-repository={{ .Values.modelRepository.mountPath }}
            - --model-control-mode=explicit
            - --http-port=8000
            - --grpc-port=8001
            - --metrics-port=8002
          ports:
            - name: http
              containerPort: 8000
            - name: grpc
              containerPort: 8001
            - name: metrics
              containerPort: 8002
          resources:
{{ toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: model-repo
              mountPath: {{ .Values.modelRepository.mountPath }}
      volumes:
        - name: model-repo
          persistentVolumeClaim:
            claimName: {{ .Values.modelRepository.pvc.name }}

