apiVersion: v1
kind: Service
metadata:
  name: triton
  labels:
    app: triton
    env: {{ .Values.global.env | quote }}
    release: {{ .Values.monitoring.releaseLabel | quote }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: triton
  ports:
    - name: http
      port: {{ .Values.service.ports.http | default 8000 }}
      targetPort: 8000
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.ports.grpc | default 8001 }}
      targetPort: 8001
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.ports.metrics | default 8002 }}
      targetPort: 8002
      protocol: TCP
