apiVersion: v1
kind: Service
metadata:
  name: triton
  labels:
{{ include "triton.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
{{ include "triton.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http | default 8000 }}
      targetPort: 8000
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.ports.grpc | default 8001 }}
      targetPort: 8001
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.ports.metrics | default 8002 }}
      targetPort: 8002
      protocol: TCP

