{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: triton
  labels:
    release: {{ .Values.monitoring.releaseLabel | quote }}
    app: triton
    env: {{ .Values.global.env | quote }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: triton
      env: {{ .Values.global.env | quote }}
  endpoints:
    - port: metrics
      interval: {{ .Values.monitoring.scrapeInterval | default "30s" }}
      path: /metrics
{{- end }}
