{{- $m := .Values.monitoring | default dict -}}
{{- if (get $m "enabled" | default false) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: triton
  labels:
{{ include "triton.labels" . | nindent 4 }}
    release: {{ (get $m "releaseLabel" | default "monitoring") | quote }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
{{ include "triton.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ (get $m "scrapeInterval" | default "30s") | quote }}
      path: /metrics
{{- end }}
