{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: triton
  labels:
{{ include "triton.labels" . | nindent 4 }}
    release: {{ default "monitoring" .Values.monitoring.releaseLabel | quote }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
{{ include "triton.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.monitoring.scrapeInterval | default "30s" }}
      path: /metrics
{{- end }}

