{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: triton
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    release: {{ .Values.monitoring.releaseLabel | quote }}
    app: triton
spec:
  namespaceSelector:
    matchNames:
      - triton-{{ .Values.global.env }}
  selector:
    matchLabels:
      app: triton
      env: {{ .Values.global.env | quote }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.monitoring.scrapeInterval | default "30s" }}
{{- end }}
