minio:
  image:
    registry: public.ecr.aws
    repository: bitnami/minio
    tag: "2025.7.23-debian-12-r3"
    pullPolicy: IfNotPresent

  auth:
    existingSecret: minio-prod
    rootUserSecretKey: root-user
    rootPasswordSecretKey: root-password

  defaultBuckets: "loki-chunks,loki-ruler,loki-admin"

  persistence:
    enabled: true
    storageClass: nfs-core
    storageClassName: nfs-core
    size: 10Gi

  service:
    type: ClusterIP

  console:
    enabled: false

  global:
    security:
      allowInsecureImages: true
